# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180311_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='troop',
            old_name='number',
            new_name='troop_number',
        ),
    ]
