# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180311_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='state_ID',
            new_name='state_name',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='state_ID',
            new_name='state_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='state_ID',
        ),
    ]
