# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180311_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='descrption',
            new_name='description',
        ),
    ]
