# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180311_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='street_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
