# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180312_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='payment_link',
            new_name='payment_url',
        ),
    ]
