# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180312_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
    ]
