# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-12 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180312_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Region'),
            preserve_default=False,
        ),
    ]
