# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-12 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_event_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='state_name',
        ),
        migrations.AlterField(
            model_name='district',
            name='district_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
