# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-12 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180511_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='region',
        ),
        migrations.AddField(
            model_name='event',
            name='district',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.District'),
            preserve_default=False,
        ),
    ]
