# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-16 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180511_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('date_start', models.DateField(blank=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.District')),
                ('event_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.EventType')),
                ('primary_contact_ID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Person')),
            ],
        ),
    ]
