# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-25 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180515_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchevent',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
