# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180524_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchevent',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.District'),
        ),
    ]
