# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180601_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchevent',
            name='date_start',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
