# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180601_2321'),
        ('app', '0018_auto_20180601_2037'),
    ]

    operations = [
    ]
