# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_autofill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='event',
            name='coord_x',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='coord_y',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
    ]
