# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20180602_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_location',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
