# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20180602_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='payment_url',
            field=models.URLField(default='https://www.'),
        ),
    ]
