# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 00:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20180602_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='autofill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(default='', max_length=100)),
                ('abbreviation', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time_start',
        ),
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='payment_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='person',
            name='state_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.State'),
            preserve_default=False,
        ),
    ]
