# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20180602_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
