# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_listevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
