# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20180602_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(default='Address not provided', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='Description not provided'),
        ),
        migrations.AlterField(
            model_name='event',
            name='payment_url',
            field=models.URLField(default='Payment link not provided'),
        ),
        migrations.AlterField(
            model_name='event',
            name='primary_contact_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Person'),
        ),
    ]
