# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20180602_2231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='autofill',
        ),
    ]
