# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20180605_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='abbreviation',
            field=models.CharField(default='', max_length=6),
        ),
    ]
