# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_region_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(default='', help_text='Enter the address of the event', max_length=500),
        ),
    ]
