# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 03:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0039_auto_20180605_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='state_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='troop_number',
        ),
        migrations.RemoveField(
            model_name='event',
            name='primary_contact_ID',
        ),
        migrations.AddField(
            model_name='event',
            name='primary_contact_info',
            field=models.CharField(default='', help_text='Contact information for event lead', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='primary_contact_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='troop',
            name='district',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.District'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='district',
            name='pointman_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchevent',
            name='primary_contact_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='troop',
            name='admin_ID',
        ),
        migrations.AddField(
            model_name='troop',
            name='admin_ID',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='leader',
            name='troop_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Troop'),
        ),
        migrations.AddField(
            model_name='leader',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
