# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20180605_2008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leader',
            new_name='Profile',
        ),
    ]
