# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20180605_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='district_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='region_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state_name',
            new_name='name',
        ),
    ]
