# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20180605_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='troop_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Troop'),
        ),
    ]
