# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20180605_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='troop',
            name='state',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.State'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='troop_number',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Troop'),
        ),
    ]
