# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20180605_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='primary_contact_info_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
