# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_event_primary_contact_info_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='primary_contact_info',
            field=models.CharField(default='', help_text='(123) 333-4445', max_length=255),
        ),
    ]
