# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20180606_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='payment_url',
            field=models.URLField(blank=True, default='https://www.', null=True),
        ),
    ]
