# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20180606_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='start',
        ),
        migrations.AddField(
            model_name='profile',
            name='permissions',
            field=models.IntegerField(default=0),
        ),
    ]
