# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20180609_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('level_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='permissions',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.PermissionLevel'),
        ),
    ]
