# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20180609_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='district',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.District'),
        ),
    ]
